/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IconMaterialSymbols:10kSharp': typeof import('~icons/material-symbols/10k-sharp')['default']
    'IconMaterialSymbols:123': typeof import('~icons/material-symbols/123')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    'IconSolar:4kBold': typeof import('~icons/solar/4k-bold')['default']
    ICustomVue: typeof import('~icons/custom/vue')['default']
    'IMaterialSymbols:10kSharp': typeof import('~icons/material-symbols/10k-sharp')['default']
    'IMaterialSymbols:123': typeof import('~icons/material-symbols/123')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiAlarmOff: typeof import('~icons/mdi/alarm-off')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseAutoImport: typeof import('./../src/components/useAutoImport.vue')['default']
    UseI18n: typeof import('./../src/components/useI18n.vue')['default']
    UseIconify: typeof import('./../src/components/useIconify.vue')['default']
    UseJsx: typeof import('./../src/components/useJsx.vue')['default']
    UseScss: typeof import('./../src/components/useScss.vue')['default']
    UseStandard: typeof import('./../src/components/useStandard.vue')['default']
    UseStore: typeof import('./../src/components/useStore.vue')['default']
    UseUnocss: typeof import('./../src/components/useUnocss.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
